spring:
  application:
    name: smartwallet-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/smartwallet_auth
    username: smartwallet
    password: smartwallet
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG

security:
  jwt:
    issuer: smartwallet-auth-service
    access-token-ttl: PT15M
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem