services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: smartwallet-auth-postgres
    environment:
      POSTGRES_DB: smartwallet_auth
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet
    ports:
      - "5433:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartwallet -d smartwallet_auth"]
      interval: 5s
      timeout: 5s
      retries: 10

  finance-postgres:
    image: postgres:16-alpine
    container_name: smartwallet-finance-postgres
    environment:
      POSTGRES_DB: smartwallet_finance
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet
    ports:
      - "5434:5432"
    volumes:
      - finance-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartwallet -d smartwallet_finance"]
      interval: 5s
      timeout: 5s
      retries: 10

  budget-postgres:
    image: postgres:16-alpine
    container_name: smartwallet-budget-postgres
    environment:
      POSTGRES_DB: smartwallet_budget
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet
    ports:
      - "5435:5432"
    volumes:
      - budget-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartwallet -d smartwallet_budget"]
      interval: 5s
      timeout: 5s
      retries: 10

  notification-postgres:
    image: postgres:16-alpine
    container_name: smartwallet-notification-postgres
    environment:
      POSTGRES_DB: smartwallet_notification
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet
    ports:
      - "5436:5432"
    volumes:
      - notification-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U smartwallet -d smartwallet_notification"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  analytics-postgres:
    image: postgres:16-alpine
    container_name: smartwallet-analytics-postgres

    environment:
      POSTGRES_DB: smartwallet_analytics
      POSTGRES_USER: smartwallet
      POSTGRES_PASSWORD: smartwallet

    ports:
      - "5437:5432"

    volumes:
      - analytics-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U smartwallet -d smartwallet_analytics"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: smartwallet-rabbitmq
    container_name: smartwallet-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: smartwallet
      RABBITMQ_DEFAULT_PASS: smartwallet

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile

    container_name: smartwallet-analytics-service
    restart: unless-stopped

    environment:
      ANALYTICS_DB_URL: jdbc:postgresql://analytics-postgres:5432/smartwallet_analytics
      ANALYTICS_DB_USERNAME: smartwallet
      ANALYTICS_DB_PASSWORD: smartwallet

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: smartwallet
      RABBITMQ_PASSWORD: smartwallet
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

    secrets:
      - jwt_public_key

    ports:
      - "8085:8085"

    depends_on:
      analytics-postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8085/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile

    container_name: smartwallet-auth-service
    restart: unless-stopped

    environment:
      AUTH_DB_URL: jdbc:postgresql://auth-postgres:5432/smartwallet_auth
      AUTH_DB_USERNAME: smartwallet
      AUTH_DB_PASSWORD: smartwallet

      JWT_PRIVATE_KEY_LOCATION: file:/run/secrets/jwt_private_key
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

    secrets:
      - jwt_private_key
      - jwt_public_key

    ports:
      - "8081:8081"

    depends_on:
      auth-postgres:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8081/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  finance-service:
    build:
      context: ./finance-service
      dockerfile: Dockerfile

    container_name: smartwallet-finance-service
    restart: unless-stopped

    environment:
      FINANCE_DB_URL: jdbc:postgresql://finance-postgres:5432/smartwallet_finance
      FINANCE_DB_USERNAME: smartwallet
      FINANCE_DB_PASSWORD: smartwallet

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: smartwallet
      RABBITMQ_PASSWORD: smartwallet
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

      RECURRING_TRANSACTION_SCHEDULER_DELAY_MS: 5000
      RECURRING_RETRY_MAX_ATTEMPTS: 3
      RECURRING_RETRY_FIRST_DELAY: PT2S
      RECURRING_RETRY_SECOND_DELAY: PT2S
    secrets:
      - jwt_public_key

    ports:
      - "8082:8082"

    depends_on:
      finance-postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8082/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

  budget-service:
    build:
      context: ./budget-service
      dockerfile: Dockerfile

    container_name: smartwallet-budget-service
    restart: unless-stopped

    environment:
      BUDGET_DB_URL: jdbc:postgresql://budget-postgres:5432/smartwallet_budget
      BUDGET_DB_USERNAME: smartwallet
      BUDGET_DB_PASSWORD: smartwallet

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: smartwallet
      RABBITMQ_PASSWORD: smartwallet

      FINANCE_SERVICE_URL: http://finance-service:8082
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

    secrets:
      - jwt_public_key
    ports:
      - "8083:8083"

    depends_on:
      budget-postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8083/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile

    container_name: smartwallet-notification-service
    restart: unless-stopped

    environment:
      NOTIFICATION_DB_URL: jdbc:postgresql://notification-postgres:5432/smartwallet_notification
      NOTIFICATION_DB_USERNAME: smartwallet
      NOTIFICATION_DB_PASSWORD: smartwallet

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: smartwallet
      RABBITMQ_PASSWORD: smartwallet
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

    secrets:
      - jwt_public_key
    ports:
      - "8084:8084"

    depends_on:
      notification-postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8084/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 25s

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    container_name: smartwallet-api-gateway
    restart: unless-stopped

    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      FINANCE_SERVICE_URL: http://finance-service:8082
      BUDGET_SERVICE_URL: http://budget-service:8083
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
      ANALYTICS_SERVICE_URL: http://analytics-service:8085
      JWT_PUBLIC_KEY_LOCATION: file:/run/secrets/jwt_public_key

    secrets:
      - jwt_public_key
    ports:
      - "8080:8080"

    depends_on:
      auth-service:
        condition: service_healthy

      finance-service:
        condition: service_healthy

      budget-service:
        condition: service_healthy

      notification-service:
        condition: service_healthy

      analytics-service:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  auth-postgres-data:
  finance-postgres-data:
  budget-postgres-data:
  notification-postgres-data:
  rabbitmq-data:
  analytics-postgres-data:

secrets:
  jwt_private_key:
    file: ./secrets/jwt/private.pem

  jwt_public_key:
    file: ./secrets/jwt/public.pem