spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**, /api/users/**


server:
  port: 8080

security:
  jwt:
    issuer: smartwallet-auth-service
    public-key: classpath:keys/public.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info
