apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-config

data:
  NOTIFICATION_DB_URL: "jdbc:postgresql://notification-postgres:5432/smartwallet_notification"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  JWT_PUBLIC_KEY_LOCATION: "file:/run/secrets/jwt_public_key"
