apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-postgres

  template:
    metadata:
      labels:
        app: notification-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: smartwallet_notification

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: NOTIFICATION_DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: NOTIFICATION_DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: notification-postgres-pvc
