apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: smartwallet-gateway:1.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          envFrom:
            - configMapRef:
                name: api-gateway-config

          volumeMounts:
            - name: jwt-public-key
              mountPath: /run/secrets/jwt_public_key
              subPath: jwt_public_key
              readOnly: true

      volumes:
        - name: jwt-public-key
          secret:
            secretName: jwt-public-key
