apiVersion: v1
kind: ConfigMap

metadata:
  name: finance-config

data:
  FINANCE_DB_URL: "jdbc:postgresql://finance-postgres:5432/smartwallet_finance"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"


  JWT_PUBLIC_KEY_LOCATION: "file:/run/secrets/jwt_public_key"
  RECURRING_TRANSACTION_SCHEDULER_DELAY_MS: "60000"
  RECURRING_RETRY_MAX_ATTEMPTS: "3"
  RECURRING_RETRY_FIRST_DELAY: "PT1M"
  RECURRING_RETRY_SECOND_DELAY: "PT5M"
