apiVersion: apps/v1
kind: Deployment

metadata:
  name: finance-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: finance-service

  template:
    metadata:
      labels:
        app: finance-service

    spec:
      containers:
        - name: finance-service
          image: ghcr.io/mertdikdas/smartwallet-finance:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 15

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: finance-config

            - secretRef:
                name: finance-secret

          volumeMounts:
            - name: jwt-public-key
              mountPath: /run/secrets/jwt_public_key
              subPath: jwt_public_key
              readOnly: true

      volumes:
        - name: jwt-public-key
          secret:
            secretName: jwt-public-key
