apiVersion: v1
kind: ConfigMap

metadata:
  name: analytics-config

data:
  ANALYTICS_DB_URL: "jdbc:postgresql://analytics-postgres:5432/smartwallet_analytics"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  JWT_PUBLIC_KEY_LOCATION: "file:/run/secrets/jwt_public_key"
