apiVersion: apps/v1
kind: Deployment

metadata:
  name: analytics-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: analytics-service

  template:
    metadata:
      labels:
        app: analytics-service

    spec:
      containers:
        - name: analytics-service
          image: smartwallet-analytics:1.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8085

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: analytics-config

            - secretRef:
                name: analytics-secret

          volumeMounts:
            - name: jwt-public-key
              mountPath: /run/secrets/jwt_public_key
              subPath: jwt_public_key
              readOnly: true

      volumes:
        - name: jwt-public-key
          secret:
            secretName: jwt-public-key
